const data = {
  products: [
    {
      _id: '1',
      name: 'Star Wars Master Yoda Mug',
      category: 'Mugs',
      image: '/images/p1.jpg',
      price: 19.95,
      countInStock: 10,
      brand: 'Etsy',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Darth Vader T-Shirt',
      category: 'T-Shirts & Tops',
      image: '/images/p2.jpg',
      price: 26.99,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'The Mandalorian Figure',
      category: 'Figures',
      image: '/images/p3.jpg',
      price: 32.99,
      countInStock: 0,
      brand: 'Disney',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Obi-Wans Hut Building Set',
      category: 'Toys',
      image: '/images/p4.jpg',
      price: 29.99,
      countInStock: 15,
      brand: 'Lego',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Darth Vader Costume',
      category: 'Costumes',
      image: '/images/p5.jpg',
      price: 31.49,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Rey LIGHTSABER Toy – Star Wars',
      category: 'Costume Accessories',
      image: '/images/p6.jpg',
      price: 32.99,
      countInStock: 12,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
